Remove formik render from fields
MyCryptoHQ/MyCrypto pull request #3475
Opened 2020-08-26 15:08 UTC by vilsbole

`render` is also deprecated for `Field`.
Replace with child callback.

2020-08-27 12:18 UTC, FrederikBolding requested changes

2020-08-27 12:18 UTC, FrederikBolding commented on src/features/DeFiZap/components/ZapForm.tsx
> +                          //handleGasEstimate();
Can we remove this?

2020-08-27 17:25 UTC, vilsbole commented on src/features/DeFiZap/components/ZapForm.tsx
> +                          //handleGasEstimate();
Done

2020-08-28 11:13 UTC, FrederikBolding approved these changes

2020-08-28 11:13 UTC, merged