Curate utils folder
MyCryptoHQ/MyCrypto pull request #3506
Opened 2020-09-09 20:44 UTC by blurpesec

[ch6835]

### Description
Removes some unused utils and increase unit test coverage.

2020-09-10 16:09 UTC, vilsbole requested changes

2020-09-10 16:09 UTC, vilsbole commented on src/utils/validators.spec.ts
> +describe('isValidUuid', () => {
Can we opt simplify the name to `isUuid`?

2020-09-10 16:09 UTC, vilsbole commented on src/utils/validators.spec.ts
> +    expect(isValidUuid(testUuid)).toBeTruthy();
When testing a method that returns a boolean, it seems more direct to assert with `toBe(true)` or `toEqual(true)`.
It avoids any ambiguity on the return value of the function.

2020-09-10 16:09 UTC, vilsbole commented on src/utils/validators.spec.ts
> +      result: true
It's not really the `result`.
Since we're in jest land, lets rename the param to `expected`.
```
{
  value: '0x',
  expected: true
}
```

2020-09-14 19:11 UTC, blurpesec commented on src/utils/buildBalanceDisplays.spec.ts
> +  });
> With composition we can most likely reduce the number of arguments.

I'm not sure i understood what you were talking about here, but i made some changes. Were you talking about refactoring `totals`?

2020-09-15 12:02 UTC, vilsbole requested changes

2020-09-15 12:02 UTC, vilsbole commented on src/utils/buildBalanceDisplays.ts
> +  } as Balance;
Don't cast the return value (it nullifies the entire use of TS).
Prefer typing the return value of the function.

2020-09-15 12:02 UTC, vilsbole commented on src/utils/buildBalanceDisplays.ts
> +    fiatValue: convertToFiatFromAsset(asset, exchangeRate),
We should never store a float in memory.
Preserve a BN, or if it's only a view helper, store a string.

2020-09-16 00:32 UTC, blurpesec commented on src/utils/emailFormatter.spec.ts
> +    )}&body=${encodeURIComponent(`Stack Trace: \n ${stackTrace}`)}`;
> Is the result really a nested 'Stack Trace: \n Stack Trace: \n test stack trace'?

yup

2020-09-17 12:23 UTC, vilsbole requested changes

2020-09-17 12:23 UTC, vilsbole commented on src/utils/buildBalanceDisplays.ts
> +      return sum + parseFloat(asset.fiatValue);
Parse float is limited to (9 * 10^15) or 15 decimals places.
Use BN math.
https://stackoverflow.com/questions/43504180/javascript-parsefloat-force-2-decimals-as-number

2020-09-17 12:23 UTC, vilsbole commented on src/features/Dashboard/components/WalletBreakdown/WalletBreakdownView.tsx
> +                      {!isOther && `${parseFloat(amount).toFixed(4)} ${ticker}`}
We can use `Currency` component for displaying.

2020-09-17 12:23 UTC, vilsbole commented on src/features/Dashboard/components/WalletBreakdown/WalletBreakdownView.tsx
> +    parseFloat(((parseFloat(balance.fiatValue) / parseFloat(totalFiatValue)) * 100).toFixed(2));
BN math

2020-09-17 12:23 UTC, vilsbole commented on src/components/BalanceDetailsTable.tsx
> +      {`${parseFloat(balance.amount).toFixed(6)} ${balance.ticker}`}
Use `Currency` or `Amount` to display value

2020-09-17 12:23 UTC, vilsbole commented on src/features/Dashboard/components/WalletBreakdown/WalletBreakdownView.tsx
> +      parseFloat(balanceObject.fiatValue) / totalFiatValue >= SMALLEST_CHART_SHARE_SUPPORTED
BN math

2020-09-17 12:23 UTC, vilsbole commented on src/features/Dashboard/components/WalletBreakdown/WalletBreakdownView.tsx
> +      parseFloat(balanceObject.fiatValue) / totalFiatValue < SMALLEST_CHART_SHARE_SUPPORTED
BN math

2020-09-18 16:12 UTC, vilsbole requested changes
Pie Chart is not visible:
<img width="814" alt="Screenshot 2020-09-18 at 18 11 26" src="https://user-images.githubusercontent.com/2429708/93620555-7b988000-f9da-11ea-9be7-329af7591236.png">

2020-09-18 16:55 UTC, blurpesec commented
> Pie Chart is not visible:
> <img alt="Screenshot 2020-09-18 at 18 11 26" width="814" src="https://user-images.githubusercontent.com/2429708/93620555-7b988000-f9da-11ea-9be7-329af7591236.png">

chart lib isnt able to sort anything other than numbers lol :shrug:

2020-09-18 16:55 UTC, vilsbole approved these changes

2020-09-18 18:35 UTC, merged