[WIP] Check Allowance before doing approvals
MyCryptoHQ/MyCrypto pull request #3524
Opened 2020-09-16 13:40 UTC by FrederikBolding

WIP

2020-09-16 13:40 UTC, FrederikBolding commented
[ch6865]

2020-09-21 11:41 UTC, vilsbole requested changes

2020-09-21 11:41 UTC, vilsbole commented on src/utils/useTxMulti/actions.ts
> +          return !hasAllowance;
unecessary variable

2020-09-21 11:41 UTC, vilsbole commented on src/utils/useTxMulti/actions.ts
> +          const hasAllowance = bigify(allowance).gte(bigify(_value));
invert comparison

2020-09-21 11:41 UTC, vilsbole commented on src/utils/asyncFilter.ts
> +};
Test Please

2020-09-21 12:42 UTC, vilsbole approved these changes

2020-09-21 12:42 UTC, merged