[WIP] Refactor SettingsProvider and test
MyCryptoHQ/MyCrypto pull request #3531
Opened 2020-09-18 11:45 UTC by FrederikBolding

- [x] Refactor to hook
- [x] Refactor app usage
- [ ] Add tests

2020-09-18 14:00 UTC, FrederikBolding commented
[ch6819]

2020-09-21 10:44 UTC, vilsbole requested changes

2020-09-21 10:46 UTC, FrederikBolding commented on jest_config/__fixtures__/localstorage.ts
> +export const fLocalStorage = {
Would using `defaultValues` instead of the fixture be fine?

2020-09-21 11:30 UTC, vilsbole approved these changes

2020-09-21 11:30 UTC, merged