Update eth-scan to 3.1.1
MyCryptoHQ/MyCrypto pull request #3551
Opened 2020-10-01 14:22 UTC by Mrtenz

2020-10-01 14:54 UTC, FrederikBolding requested changes

2020-10-01 14:54 UTC, FrederikBolding commented on src/services/Store/BalanceService.tsx
> +  console.log(bn);
Please remove 😄

2020-10-01 14:54 UTC, FrederikBolding commented on src/services/Store/StoreProvider.tsx
> +// @todo: Update unlock-scan to use native bigints like eth-scan
Can we do this now such that we don't have to duplicate converting logic?

2020-10-01 14:54 UTC, FrederikBolding commented on src/services/Store/StoreProvider.tsx
> +// @todo: Update unlock-scan to use native bigints like eth-scan
If not, please move this to a helper and test.

2020-10-01 15:12 UTC, GuillaumeRx commented on src/services/Store/BalanceService.tsx
> +    return getTokensBalance(provider, address, contractList, options);
Missing to await ?

2020-10-01 15:12 UTC, GuillaumeRx commented on src/services/Store/BalanceService.tsx
> +    return getEtherBalances(provider, [address], options);
Missing to await ?

2020-10-01 16:56 UTC, Mrtenz commented on src/services/Store/BalanceService.tsx
> +  console.log(bn);
Fixed

2020-11-30 18:47 UTC, FrederikBolding commented
Still WIP according to @Mrtenz

2021-01-05 00:00 UTC, FrederikBolding approved these changes

2021-01-05 00:10 UTC, merged