[WIP] AAVE migration
MyCryptoHQ/MyCrypto pull request #3575
Opened 2020-10-23 13:29 UTC by FrederikBolding

2020-10-23 13:45 UTC, FrederikBolding commented
[ch7145]

2020-10-29 14:00 UTC, FrederikBolding commented
Has not been tested yet due to gas prices, but good for code review @blurpesec

2020-10-30 20:51 UTC, blurpesec requested changes
I went through the whole flow. It approved the correct amount, but migrated the wrong amount.

After you proceed past the flow is it supposed to remove the user action from the table? Also, I think it didn't re-scan the account for token balances post-migration success.

2020-10-30 20:51 UTC, blurpesec commented on src/features/AaveTokenMigration/helpers.ts
> +  const data = AaveMigrator.migrateFromLEND.encodeInput({ amount: payload.amount });
I'm assuming this is where the wrong amount came in. Here was my test approve tx: https://etherscan.io/tx/0x5ecb4ea41154b1a8f6cc3cb8af5f7162f33cd59c92708b337fc69efd67310e17
And my test migrate tx: https://etherscan.io/tx/0x4be2459a0fe228764f675b337d8228452d2a04e448cb32c166b42ba8327d180e

2020-11-03 19:05 UTC, blurpesec approved these changes

2020-11-03 19:06 UTC, merged

2020-11-03 20:40 UTC, FrederikBolding commented
Successfully tested flow: https://etherscan.io/tx/0x92c711003696a3d08289df931bd87b408186d078215649801d7189f6a944a785