Membership slice and start of membership saga
MyCryptoHQ/MyCrypto pull request #3657
Opened 2020-12-03 18:05 UTC by vilsbole

- Create membership slice.
- Extract membership lookup into saga.
- Test!

2020-12-03 19:34 UTC, GuillaumeRx requested changes

2020-12-03 19:34 UTC, GuillaumeRx commented on src/features/AddAccount/AddAccountFlow.tsx
> +              dispatch(fetchMemberships([...newAccounts]));
why destructuring `newAccounts` ?

2020-12-04 12:36 UTC, vilsbole commented on src/features/AddAccount/AddAccountFlow.tsx
> +              dispatch(fetchMemberships([...newAccounts]));
Done

2020-12-04 12:52 UTC, GuillaumeRx approved these changes
LGTM

2020-12-04 12:56 UTC, merged