Generic Hardware Wallet Errors
MyCryptoHQ/MyCrypto pull request #3668
Opened 2020-12-11 00:04 UTC by blurpesec

### Description
Introduces better error messaging for hardware wallet unlock errors.

##### Screenshots
![Selection_024](https://user-images.githubusercontent.com/29407814/101844474-59a62980-3b01-11eb-9517-5a8945fef552.png)

2020-12-15 23:03 UTC, vilsbole requested changes
Love the scss deletions!

2021-01-05 15:01 UTC, GuillaumeRx commented
Can we center the error text ?

2021-01-05 21:06 UTC, blurpesec commented on src/components/Icon/Icon.tsx
> +  'trezor-icon-lg': trezorLgIcon,
They're different.

2021-01-05 21:15 UTC, blurpesec commented on src/components/SignTransactionWallets/Hardware.stories.tsx
> +export default { title: 'SignTransaction' };
Can't see this in storybook unless i have exports on these.

2021-01-05 21:15 UTC, blurpesec commented on src/components/SignTransactionWallets/Hardware.stories.tsx
> +export const HardwareWalletUI = () => {
reference https://github.com/MyCryptoHQ/MyCrypto/pull/3668#discussion_r552198847

2021-01-05 21:15 UTC, blurpesec commented on src/components/WalletUnlock/Ledger.stories.tsx
> +export default { title: 'WalletUnlock/LedgerNanoS' };
reference https://github.com/MyCryptoHQ/MyCrypto/pull/3668#discussion_r552198847

2021-01-05 21:15 UTC, blurpesec commented on src/components/WalletUnlock/Ledger.stories.tsx
> +export const LedgerPanel = () => {
reference https://github.com/MyCryptoHQ/MyCrypto/pull/3668#discussion_r552198847

2021-01-05 23:34 UTC, blurpesec commented on src/components/WalletUnlock/NewTrezor.tsx
consolidated the UI portions

2021-01-05 23:35 UTC, blurpesec commented on src/components/WalletUnlock/NewTrezor.tsx
> +            <img src={ConnectTrezor} />
Yeh.

2021-01-07 11:00 UTC, GuillaumeRx approved these changes

2021-01-07 20:52 UTC, merged