Simplify node selection
MyCryptoHQ/MyCrypto pull request #3725
Opened 2021-01-13 12:51 UTC by FrederikBolding

2021-01-13 12:51 UTC, FrederikBolding commented
[ch7591]

2021-01-13 16:08 UTC, vilsbole requested changes

2021-01-13 16:08 UTC, vilsbole commented on src/components/NetworkNodeDropdown.tsx
>    const displayNodes = [autoNode, ...nodes, ...(isFunction(onEdit) ? [{ service: newNode }] : [])];
In fact a `Selector` has a `getOptionLabel` prop which removes the need to remap options to { label, value } so we don't need to destructure `selectedNode` and we can write:

```
<Selector<NodeOptions & any>
  getOptionLabel={(n) => n.service || n.name}
  value={selectedNode}
  options={displayNodes}
  ...
```

The change is small, it removes a superfluous `map` + intermediate variables and only requires remapping the displayed properties in `optionComponent` and `valueComponent`. A useful example of this technique is `AssetSelector`.

2021-01-13 16:29 UTC, FrederikBolding commented on src/services/Store/store/persist.config.ts
> +  2: (state: DataStore) => {
The API requires a `number`, so this is impossible.

2021-01-13 16:30 UTC, FrederikBolding commented on src/services/Store/store/persist.config.ts
> +        autoNode: undefined,
Sure, is there a pretty way to do it in a map? I couldn't think of one, hence I just used `undefined`.

2021-01-14 12:15 UTC, FrederikBolding commented on src/components/NetworkNodeDropdown.tsx
>    const displayNodes = [autoNode, ...nodes, ...(isFunction(onEdit) ? [{ service: newNode }] : [])];
I don't agree entirely with your simplification of removing `autoNode` fx. I think it is clearer with that. But I have simplified further.

2021-01-14 12:43 UTC, vilsbole commented on src/services/Store/store/persist.config.ts
> +  2: (state: DataStore) => {
Ok 👍

2021-01-14 12:44 UTC, vilsbole commented on src/services/Store/store/persist.config.ts
> +        autoNode: undefined,
In es6 destructuring works well for this.
```
networks: state.networks.map(({ autoNode, ...n }) => ({ ...n })
```

2021-01-14 12:47 UTC, FrederikBolding commented on src/services/Store/store/persist.config.ts
> +        autoNode: undefined,
Duh, thanks 😆

2021-01-14 12:57 UTC, vilsbole approved these changes

2021-01-14 13:02 UTC, merged