[WIP] Misc styling fixes
MyCryptoHQ/MyCrypto pull request #3754
Opened 2021-01-21 15:04 UTC by FrederikBolding

2021-01-21 15:05 UTC, FrederikBolding commented
[ch7628]

2021-01-21 16:41 UTC, GuillaumeRx approved these changes

2021-01-21 16:41 UTC, GuillaumeRx commented on src/components/RouterLink.tsx
> +  color: ${COLORS.BLUE_SKY} !important;
use ampersands (`&&&`) instead of `!important`

https://styled-components.com/docs/faqs#how-can-i-override-styles-with-higher-specificity

2021-01-21 16:41 UTC, GuillaumeRx requested changes
Miss clicked last time

2021-01-21 16:47 UTC, GuillaumeRx commented
Links shouldn't be underlined

![Screenshot 2021-01-21 at 17 46 32](https://user-images.githubusercontent.com/13910212/105382688-a278f400-5c10-11eb-8c5d-021876d1f2a1.png)

2021-01-23 22:50 UTC, GuillaumeRx approved these changes

2021-01-24 12:04 UTC, merged