[WIP] Flow Footers
MyCryptoHQ/MyCrypto pull request #3770
Opened 2021-01-25 20:35 UTC by FrederikBolding

2021-01-25 20:35 UTC, FrederikBolding commented
[ch7784]

2021-01-26 12:38 UTC, GuillaumeRx requested changes

2021-01-26 12:38 UTC, GuillaumeRx commented on src/components/FlowFooter.tsx
> +}
Can this go to config ?

2021-01-26 12:38 UTC, GuillaumeRx commented on src/components/FlowFooter.tsx
> +import { Link } from './NewTypography';
from `@components`

2021-01-26 12:38 UTC, GuillaumeRx commented on src/components/FlowFooter.tsx
> +};
This should go to config or in a constant file of you want to keep it near the component :)

2021-01-26 13:19 UTC, GuillaumeRx approved these changes
lgtm

2021-01-26 19:00 UTC, GuillaumeRx submitted a review, later dismissed

2021-01-26 23:06 UTC, GuillaumeRx submitted a review, later dismissed

2021-01-27 14:52 UTC, merged