Allows multiple assets to share the same coingeckoid
MyCryptoHQ/MyCrypto pull request #3864
Opened 2021-02-25 01:28 UTC by blurpesec

### Description
Improves our handling of rates.

### Changes:
1) Improves processing of rates by decreasing scope of iterations to relevant entries (was previously looping through all assets, now it only loops through assets user has that have coingeckoids - This was an issue because this loop would occur 3-4 times on initial page load based on settings changes).
2) Allows multiple assets to use the same coingeckoid (previously didn't allow this).

2021-02-25 10:03 UTC, FrederikBolding requested changes

2021-02-25 10:03 UTC, FrederikBolding commented on src/services/Rates/RatesProvider.tsx
> +    relevantAssets.forEach(([assetUuid, _]) => (acc[assetUuid] = rates[curValue]));
Can we do this using a `reduce`?

2021-02-25 10:03 UTC, FrederikBolding commented on src/services/Rates/RatesProvider.tsx
> +interface GeckoIds {
Can we just use `Record` instead of defining a new type?

2021-02-25 10:03 UTC, FrederikBolding commented on src/services/Rates/RatesProvider.tsx
> +      buildAssetQueryUrl(Object.values(geckoIds), Object.keys(Fiats)), // @todo: More elegant conversion then `DEFAULT_FIAT_RATE`
Can we filter by unique here?

2021-02-25 10:03 UTC, FrederikBolding commented on src/services/Rates/RatesProvider.tsx
> +  }, [Object.values(geckoIds).length]);
Can we filter by unique here?

2021-02-25 17:36 UTC, GuillaumeRx commented
This will enter in conflict with the rates migration to redux :(

2021-02-25 17:41 UTC, FrederikBolding commented
> This will enter in conflict with the rates migration to redux :(

Then make sure this is reflected in your version 😊

2021-02-25 17:44 UTC, GuillaumeRx commented
> Then make sure this is reflected in your version 😊

Well... this file doesn't exist and it'll already handle assets with no coingecko ids. Those functions have also been refactored

2021-02-25 17:48 UTC, FrederikBolding commented
> > Then make sure this is reflected in your version 😊
> 
> Well... this file doesn't exist and it'll already handle assets with no coingecko ids. Those functions have also been refactored

Okay, but the fix should still be reflected in the new version. So we just need to test that this behavior is in the redux version and add it if not. It doesn't make sense to redo rates without fixing this too.

2021-02-25 17:50 UTC, GuillaumeRx commented
> Okay, but the fix should still be reflected in the new version. So we just need to test that this behavior is in the redux version and add it if not. It doesn't make sense to redo rates without fixing this too.

I totally agree with you, it just doesn't make sense to add code that will be deleted soon :)

2021-03-09 16:55 UTC, blurpesec commented
This was fixed in #3869 !

2021-03-09 16:55 UTC, closed without merging