Performance improvement when adding multiple accounts
MyCryptoHQ/MyCrypto pull request #3915
Opened 2021-04-01 16:08 UTC by blurpesec

### Description

Batch create/update contacts to decrease the number of updates we make when adding multiple accounts.

2021-04-02 10:05 UTC, vilsbole requested changes

2021-04-02 10:05 UTC, vilsbole commented on src/services/Store/Contact/useContacts.tsx
> +  };
Caller should be obnoxious of the uuid format.
Use action creator for setting the uuid.

```
type createContact(items: Contact[], generateUUID: (any) => TUuid = generateDeterministicUUID)
```

2021-04-02 10:05 UTC, vilsbole commented on src/services/Store/Contact/useContacts.tsx
> +    createContacts,
We are working to remove the hooks and let the components connect directly to the store.

2021-04-02 10:05 UTC, vilsbole commented on src/services/Store/StoreProvider.tsx
> +    createContacts,
Prefer `connect` over hook.

2021-04-02 10:05 UTC, vilsbole commented on src/services/Store/StoreProvider.tsx
> +      );
This looks like a create or update logic.
It should be the responsibility of the slice.
Move to redux.

FYI: there appears to already be a createOrUpdate defined

2021-06-09 12:26 UTC, FrederikBolding commented
Closing in favor of #4009

2021-06-09 12:26 UTC, closed without merging