[WIP] More Swap testing with hardhat
MyCryptoHQ/MyCrypto pull request #3968
Opened 2021-05-19 14:48 UTC by FrederikBolding

2021-05-20 14:35 UTC, FrederikBolding commented
[ch8598]

2021-05-21 11:22 UTC, Mrtenz requested changes

2021-05-21 11:22 UTC, Mrtenz commented on package.json
> +}
Please add a line at the end

2021-05-21 11:27 UTC, Mrtenz approved these changes

2021-05-21 11:36 UTC, merged

2021-05-21 11:36 UTC, FrederikBolding commented
[ch8598]