Move pending tx handling to Redux
MyCryptoHQ/MyCrypto pull request #4002
Opened 2021-06-04 16:11 UTC by FrederikBolding

2021-06-04 16:12 UTC, FrederikBolding commented
This still needs to be tested to make sure it works as intended when moved to a saga.

2021-06-04 16:12 UTC, FrederikBolding commented
[ch8342]

2021-06-07 13:51 UTC, GuillaumeRx requested changes

2021-06-07 13:51 UTC, GuillaumeRx commented on src/services/Store/store/account.slice.ts
> +      yield put(updateAccount(sanitizeAccount(updatedAccount)));
you don't have to call `sanitizeAccount` here, it's done in the reducer :)

2021-06-07 13:51 UTC, GuillaumeRx commented on src/services/Store/store/account.slice.ts
> +    yield put(addTxToAccount({ account: sanitizeAccount(senderAccount), tx: finishedTxReceipt }));
same here

2021-06-07 14:38 UTC, GuillaumeRx requested changes

2021-06-07 14:38 UTC, GuillaumeRx commented on src/services/Store/store/account.slice.ts
> +    const assets = getAssets(s);
can we move this in the array of selectors ?

2021-06-07 14:52 UTC, GuillaumeRx approved these changes

2021-06-07 15:21 UTC, merged