Added scrolling to account dropdown
MyCryptoHQ/MyCrypto pull request #4033
Opened 2021-06-16 23:12 UTC by blurpesec

[ch8539]

### Description
Added scrolling to account dropdown

2021-06-17 09:48 UTC, FrederikBolding requested changes
One small change

2021-06-17 09:48 UTC, FrederikBolding commented on src/features/Dashboard/components/WalletBreakdown/AccountDropdown.tsx
> +  overflow: scroll;
Can we do only scrolling on the y-axis?

2021-06-18 19:35 UTC, blurpesec commented on src/features/Dashboard/components/WalletBreakdown/AccountDropdown.tsx
> +  overflow: scroll;
yeh

2021-06-23 10:50 UTC, FrederikBolding approved these changes

2021-06-23 10:50 UTC, merged