Remove cached assets
MyCryptoHQ/MyCrypto pull request #4046
Opened 2021-07-01 10:20 UTC by FrederikBolding

2021-07-01 10:54 UTC, Mrtenz requested changes

2021-07-01 10:54 UTC, Mrtenz commented on src/services/Store/store/asset.slice.test.ts
> +    const a1 = { uuid: 'random', contractAddress: '0x0', type: 'erc20' } as ExtendedAsset;
Prefer `const a1: ExtendedAsset = { ... }` over casting with `as`.

2021-07-01 13:45 UTC, FrederikBolding commented on src/services/Store/store/asset.slice.test.ts
> +    const a1 = { uuid: 'random', contractAddress: '0x0', type: 'erc20' } as ExtendedAsset;
Will simplify by using `fAssets` instead.

2021-07-02 10:58 UTC, Mrtenz approved these changes

2021-07-02 10:58 UTC, merged