Automatically fetch token information when entering a token address
MyCryptoHQ/MyCrypto pull request #4061
Opened 2021-07-26 10:13 UTC by Mrtenz

2021-07-26 13:29 UTC, FrederikBolding requested changes

2021-07-26 13:29 UTC, FrederikBolding commented on src/helpers/erc20.ts
> +export const getTokenInformation = async (
Could we move this to `ProviderHandler` or is there a reason not to?

2021-07-26 13:29 UTC, FrederikBolding commented on src/features/Dashboard/components/TokenPanel/AddToken.tsx
> +  const handleChangeAddress = (event: ChangeEvent<HTMLInputElement>) =>
Can we test this component?

2021-07-27 15:40 UTC, Mrtenz commented
[ch8323]

2021-07-28 11:40 UTC, FrederikBolding approved these changes

2021-07-28 11:40 UTC, merged