[WIP] New Pending State
MyCryptoHQ/MyCrypto pull request #4086
Opened 2021-08-12 15:33 UTC by FrederikBolding

2021-08-12 15:34 UTC, FrederikBolding commented
[ch8780]

2021-09-05 17:44 UTC, Mrtenz requested changes

2021-09-05 17:44 UTC, Mrtenz commented on src/features/SendAssets/SendAssets.tsx
> +            payload: err.reason ? err.reason : err.message
```suggestion
            payload: err.reason ?? err.message
```

2021-09-05 17:44 UTC, Mrtenz commented on src/features/SendAssets/SendAssets.tsx
> +      onRender={(goToNextStep) => {
Don't use arrow functions in props.

2021-09-05 17:44 UTC, Mrtenz commented on src/hooks/useGasForm/useGasForm.ts
> +      setGasEstimationError(err.reason ? err.reason : err.message);
```suggestion
      setGasEstimationError(err.reason ?? err.message);
```

2021-09-08 17:53 UTC, Mrtenz requested changes

2021-09-08 17:53 UTC, Mrtenz commented on src/components/TransactionFlow/__tests__/TxReceipt.test.tsx
> +import { default as TxReceipt, TxReceiptUI } from '../TxReceipt';
```suggestion
import TxReceipt, { TxReceiptUI } from '../TxReceipt';
```

2021-09-14 15:06 UTC, Mrtenz approved these changes

2021-09-14 19:46 UTC, merged