Actions panel > completed icon
MyCryptoHQ/MyCrypto pull request #4107
Opened 2021-09-01 01:07 UTC by 409H

[CH8845]

🎉 🎉 🎉

## Description

* Updated logic to display a green tick when an action has been completed instead of a low opacity tick

## Changes

* New SVG into assets
* Code change to check state to show default icon or completed icon

### Reusable Code/Components

## Steps to Test

1. Steps
2. to
3. test

## [Zeplin Design](https://app.zeplin.io/project/5b0334f5e91e8c481645ad56)

## Quality Assurance

- [ ] The branch name is in lowercase-kebab-case with no prefix (unless it was created from Clubhouse)
- [ ] The base branch is develop or gau (no nested branches)
- [ ] This is related to a maximum of one Clubhouse story or GitHub issue
- [ ] Types are safe (avoid TypeScript/TSLint features like any and disable, instead use more specific types)
- [ ] If code is copied from existing directories, there is an explanation of why this is necesary in the description/changes, and all copying is done in separate commits to make them easy to filter out
- [ ] If your code adds new text to the UI, the added text is [translatable](https://github.com/MyCryptoHQ/MyCrypto/wiki/Contributing---Translatable-strings)

2021-09-01 09:46 UTC, FrederikBolding requested changes

2021-09-01 09:46 UTC, FrederikBolding commented on src/components/ActionsPanel/components/ActionItem.tsx
> +        <img src={IconCompleted} title="Action is completed" />
Can we add this to `Icon` instead?

2021-09-02 15:28 UTC, 409H commented on src/components/ActionsPanel/components/ActionItem.tsx
> +        <img src={IconCompleted} title="Action is completed" />
Yep, good point - check 3912380

2021-09-02 15:39 UTC, FrederikBolding approved these changes

2021-09-02 16:06 UTC, merged