Fix pending state gas increase calculation
MyCryptoHQ/MyCrypto pull request #4197
Opened 2021-11-15 14:07 UTC by FrederikBolding

2021-11-15 14:28 UTC, Mrtenz requested changes

2021-11-15 14:28 UTC, Mrtenz commented on src/utils/index.ts
> +export { default as useEffectAllDepsChange } from './useEffectAllDepsChange';
Why not just export it normally in the first place?

2021-11-15 14:28 UTC, Mrtenz commented on src/utils/useEffectAllDepsChange.ts
> +function useEffectAllDepsChange(fn: () => void, deps: unknown[]) {
Can you use an arrow function?

2021-11-15 14:32 UTC, Mrtenz approved these changes

2021-11-17 14:01 UTC, FrederikBolding commented
[sc-9232]

2021-11-17 14:23 UTC, Mrtenz approved these changes

2021-11-17 14:23 UTC, merged