Merge migrations to a single tool
MyCryptoHQ/MyCrypto pull request #4218
Opened 2021-11-30 15:06 UTC by FrederikBolding

2021-11-30 15:12 UTC, FrederikBolding commented
[sc-9143]

2021-12-02 14:28 UTC, Mrtenz requested changes

2021-12-02 14:28 UTC, Mrtenz commented on src/components/TextSelector.tsx
> +      pl={paddingLeft || '0px'}
Use a default param value

2021-12-03 13:13 UTC, Mrtenz approved these changes

2021-12-03 13:39 UTC, merged