Add Support for XinFin ( XDC ) Network.
MyCryptoHQ/MyCrypto pull request #4250
Opened 2022-01-08 11:06 UTC by BlocksScanIO

XinFin XDC.Network is an enterprise-ready hybrid Blockchain technology company optimised for international trade and finance. The XinFin XDC.network is powered by the native coin called XDC. The XDC protocol is architected to support smart contracts, 2000TPS, 2seconds transaction time, KYC to Masternodes (Validator Nodes). The XDC.Network uses XinFin Delegated Proof of Stake (XDPoS), with the intending to create a ‘highly-scalable, secure, permission, and commercial grade’ blockchain network.

Github:- https://github.com/XinFinOrg

CMC :- https://coinmarketcap.com/currencies/xinfin-network/

Docker FullNode:- https://github.com/xinfinorg/XinFin-Node

Technical Community Support available at:

Telegram Community: https://t.me/XinFinDevelopers

Slack Community: https://xinfin-public.slack.com/messages/CELR2M831/

Slack Invitation Link: https://launchpass.com/xinfin-public

Technical help Resource: http://howto.xinfin.org/

2022-01-27 03:31 UTC, BlocksScanIO commented
Hello @FrederikBolding ,

Please guide us with further step to get XDC.Network listed in MyCrypto Wallet.

2022-01-27 09:03 UTC, FrederikBolding commented
Hi! Thanks for opening the PR. I haven't had the time to look it through yet, but will try to get that done soon. Then there might be a few questions or changes requested. 

Thanks for your patience.

2022-02-14 09:31 UTC, BlocksScanIO commented
Hello @FrederikBolding, 

Just the formal followup on when can we see the XinFin XDC.Network on MyCrypto.

2022-02-15 08:46 UTC, FrederikBolding commented
> Hello @FrederikBolding,
> 
> Just the formal followup on when can we see the XinFin XDC.Network on MyCrypto.

Sorry for the delay - we've been very busy lately. Will try to get to this during this week!

2022-02-15 08:49 UTC, FrederikBolding commented
/ok-to-test

2022-02-15 08:52 UTC, FrederikBolding requested changes

2022-02-15 08:52 UTC, FrederikBolding commented on jest_config/__fixtures__/assets.ts
> +  {
There is no need to add this. Please remove 👍

2022-02-15 08:53 UTC, FrederikBolding commented
Also, if possible can you rebase your PR?

2022-02-15 08:55 UTC, BlocksScanIO commented
Changes added and updated branch. :)

2022-02-17 16:45 UTC, BlocksScanIO commented
Rebase done...!!!

2022-02-22 06:43 UTC, BlocksScanIO commented
@FrederikBolding changes has been added.

2022-02-22 09:50 UTC, FrederikBolding commented
/ok-to-test

2022-02-22 10:07 UTC, FrederikBolding approved these changes

2022-02-22 10:09 UTC, merged

2022-02-22 10:21 UTC, FrederikBolding commented
@BlocksScanIO Merged! The network will be included in our next release, probably some time this week!

2022-02-23 21:21 UTC, bowensanders commented
@BlocksScanIO Would it be possible, since we do not have any tokens for your network, for you to check a build to make sure your network is functioning properly before we push it live?
[test link](https://rc.app.MyCrypto.com)
Just add your account and perhaps do a send (to yourself or otherwise)?
Thanks!

2022-03-13 09:13 UTC, popeda97 reviewed
blocksscan:master

2022-04-06 15:32 UTC, ChainGamer commented
> @BlocksScanIO Merged! The network will be included in our next release, probably some time this week!

Hi @FrederikBolding Has this been publicly released?

2022-04-30 05:20 UTC, BlocksScanIO commented
![image](https://user-images.githubusercontent.com/88524141/166092361-99323f6e-cd44-4f3c-98ea-9915b6c2d935.png)


@ChainGamer Yes its live 👍